mongodb:
  default:
    host: localhost:27017
    db: {{ cookiecutter.project_slug }}

cors:
  origins:
    - http://localhost:3000
    - http://127.0.0.1:3000

#    For local development and debugging
#    it can be helpful to allow ALL origins
#    - *

logging:
{% if cookiecutter.logging|lower == 'logging_py3' %}
    # Listen and apply live config changes
    listen: True

    # Add your custom logging config here
    # logging_py3 provides a solid default config and advanced logging features
    # See: https://github.com/FabianElsmer/logging-py3
{% else %}
    level: DEBUG
{% endif %}
